In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.linear_model import LassoCV

In [2]:
data = pd.read_csv("/Users/soumobratamanna/Documents/AI_ML PROJECTS/car data.csv")

In [3]:
data.head(10)

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0           ritz  2014           3.35           5.59       27000    Petrol   
1            sx4  2013           4.75           9.54       43000    Diesel   
2           ciaz  2017           7.25           9.85        6900    Petrol   
3        wagon r  2011           2.85           4.15        5200    Petrol   
4          swift  2014           4.60           6.87       42450    Diesel   
5  vitara brezza  2018           9.25           9.83        2071    Diesel   
6           ciaz  2015           6.75           8.12       18796    Petrol   
7        s cross  2015           6.50           8.61       33429    Diesel   
8           ciaz  2016           8.75           8.89       20273    Diesel   
9           ciaz  2015           7.45           8.92       42367    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0  
5      Dealer       Manual      0  
6      Dealer       Manual      0  
7      Dealer       Manual      0  
8      Dealer       Manual      0  
9      Dealer       Manual      0

In [4]:
data.tail(10)

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
291     brio  2015           5.40           6.10       31427    Petrol   
292     jazz  2016           6.40           8.40       12000    Petrol   
293     city  2010           3.25           9.90       38000    Petrol   
294    amaze  2014           3.75           6.80       33019    Petrol   
295     city  2015           8.55          13.09       60076    Diesel   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
291      Dealer       Manual      0  
292      Dealer       Manual      0  
293      Dealer       Manual      0  
294      Dealer       Manual      0  
295      Dealer       Manual      0  
296      Dealer       Manual      0  
297      Dealer       Manual      0  
298      Dealer       Manual      0  
299      Dealer       Manual      0  
300      Dealer       Manual      0

In [5]:
data.shape

(301, 9)

In [6]:
data.info

<bound method DataFrame.info of     Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
0        Dealer       Manual      0  
1  

In [7]:
data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [9]:
#Encoding the fuel type
data.replace({'Fuel_Type':{'Petrol':0,'Diesel':1,'CNG':2}},inplace=True)

#Encoding the Seller  type
data.replace({'Seller_Type':{'Dealer':0,'Individual':1}},inplace=True)

#Encoding the Transmission type
data.replace({'Transmission':{'Manual':0,'Automatic':1}},inplace=True)

In [10]:
data.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven  Fuel_Type  \
0     ritz  2014           3.35           5.59       27000          0   
1      sx4  2013           4.75           9.54       43000          1   
2     ciaz  2017           7.25           9.85        6900          0   
3  wagon r  2011           2.85           4.15        5200          0   
4    swift  2014           4.60           6.87       42450          1   

   Seller_Type  Transmission  Owner  
0            0             0      0  
1            0             0      0  
2            0             0      0  
3            0             0      0  
4            0             0      0

In [12]:
X = data.drop(['Car_Name','Selling_Price'],axis=1) #Removing the 2 cols , name and the selling price from the dataset
Y = data['Selling_Price'] #Target varibale 

In [13]:
X

Year  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  Transmission  \
0    2014           5.59       27000          0            0             0   
1    2013           9.54       43000          1            0             0   
2    2017           9.85        6900          0            0             0   
3    2011           4.15        5200          0            0             0   
4    2014           6.87       42450          1            0             0   
..    ...            ...         ...        ...          ...           ...   
296  2016          11.60       33988          1            0             0   
297  2015           5.90       60000          0            0             0   
298  2009          11.00       87934          0            0             0   
299  2017          12.50        9000          1            0             0   
300  2016           5.90        5464          0            0             0   

     Owner  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
296      0  
297      0  
298      0  
299      0  
300      0  

[301 rows x 7 columns]

In [14]:
Y

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...  
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.25,random_state=42)

In [16]:
X_train

Year  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  Transmission  \
129  2017           0.84        5000          0            1             0   
232  2015          14.79       12900          0            0             1   
195  2015           0.32       35000          0            1             0   
277  2015          13.60       21780          0            0             0   
280  2015           5.90       14465          0            0             0   
..    ...            ...         ...        ...          ...           ...   
188  2013           0.57       18000          0            1             0   
71   2011          12.48       45000          1            0             0   
106  2014           3.45       16500          0            1             0   
270  2011          10.00       69341          0            0             0   
102  2017           1.78        4000          0            1             0   

     Owner  
129      0  
232      0  
195      0  
277      0  
280      0  
..     ...  
188      0  
71       0  
106      1  
270      0  
102      0  

[225 rows x 7 columns]

In [17]:
X_test

Year  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  Transmission  \
177  2016           0.57       24000          0            1             1   
289  2016          13.60       10980          0            0             0   
228  2012           9.40       60000          1            0             0   
198  2011           0.57       35000          0            1             0   
60   2013          18.61       40001          0            0             0   
..    ...            ...         ...        ...          ...           ...   
22   2011           8.01       50000          0            0             1   
286  2016           7.90       28569          0            0             0   
56   2015           7.27       40534          0            0             0   
239  2012           4.43       23709          0            0             0   
113  2016           1.40       35000          0            1             0   

     Owner  
177      0  
289      0  
228      0  
198      1  
60       0  
..     ...  
22       0  
286      0  
56       0  
239      0  
113      0  

[76 rows x 7 columns]

In [18]:
model = Lasso()

In [19]:
model.fit(X_train,y_train)

Lasso()

In [21]:
model.intercept_


-602.0949062324067

In [22]:
model.coef_

array([ 2.99550231e-01,  4.95349070e-01, -5.30198180e-06,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00, -0.00000000e+00])

In [24]:
# predictions = model.predict(X_train)

array([ 2.48749234,  8.75662574,  1.47175091,  8.12007875,  4.34467491,
        3.496464  ,  4.12528118, 13.5069182 ,  2.29576942,  2.0631963 ,
        1.81224064,  3.73421826,  1.77102726, 15.29091652,  2.13683801,
       -0.32081435,  9.82123801,  6.91519004,  3.86984595, -2.99145243,
        4.68412248,  6.64012947,  4.19145596, -1.63975001,  6.62264903,
        0.35628878,  4.98063939,  4.28618142,  9.81812897,  2.45982864,
       12.09248407,  2.43549718,  0.66166471,  1.02162769,  5.52770432,
        2.08190247,  3.83191498,  1.02118055, 14.22151421,  3.92993199,
        0.22809636, 45.4568267 ,  8.34458473,  1.60738684,  4.7035379 ,
        8.27232933,  2.56159807,  1.88137729,  6.09202419,  6.78041847,
        1.50956833,  0.14199533,  5.47287804,  3.60743263,  0.07872004,
        3.44219277,  4.2102939 ,  2.35098223,  0.9821367 ,  2.36574405,
        5.93808306,  6.30596457,  1.7929562 ,  1.3561022 ,  0.53466699,
        6.94051369,  2.13418702,  5.96421848, -0.60814819,  2.39

In [25]:
predictions = model.predict(X_test)

In [26]:
predictions

array([ 1.9534602 ,  8.47689039,  4.93832022,  0.39738725,  9.90606972,
        5.69269321,  2.08912017,  1.59274966,  1.99161955,  5.8893924 ,
        7.25576021,  1.45290584,  7.08373141,  2.34364448,  5.31740018,
        2.97981757,  1.40604596, 11.28508845,  2.31980048,  2.99202156,
        1.19768914,  6.35160134,  5.08506848,  2.66635987,  1.55710437,
        3.7780087 ,  5.50303623,  2.90106562,  2.76775036,  2.44594673,
        1.20471611,  7.80012046,  0.32848552,  2.63618786,  6.91519004,
        4.48113246,  7.78968976,  8.5912305 ,  2.78262608,  8.91973008,
        4.89193988,  3.60473299,  4.26875473,  1.37780785,  5.58652411,
        1.32446357,  7.72325836, 10.88571813,  3.01925437,  3.68717514,
        5.36406822,  2.80433404, 19.06236797, 14.59529219,  5.82964888,
        8.3720543 ,  4.29848176,  7.36420425,  2.29999263,  5.92898335,
        1.02795111, -0.36438277,  2.54993371, -0.47330242,  4.6763109 ,
        2.49525516, 18.79462963, 16.44936432,  5.42138696,  0.29

In [27]:
np.sqrt(mean_squared_error(y_test,predictions))

2.1105353273962106

In [28]:
r2_score(y_test,predictions)

0.8378718007612107