In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
df = pd.read_csv("/Users/soumobratamanna/Documents/AI_ML PROJECTS/Stars.csv")

In [3]:
df.head()

Temperature         L       R    A_M Color Spectral_Class  Type
0         3068  0.002400  0.1700  16.12   Red              M     0
1         3042  0.000500  0.1542  16.60   Red              M     0
2         2600  0.000300  0.1020  18.70   Red              M     0
3         2800  0.000200  0.1600  16.65   Red              M     0
4         1939  0.000138  0.1030  20.06   Red              M     0

In [4]:
df.tail()

Temperature         L       R    A_M  Color Spectral_Class  Type
235        38940  374830.0  1356.0  -9.93   Blue              O     5
236        30839  834042.0  1194.0 -10.63   Blue              O     5
237         8829  537493.0  1423.0 -10.73  White              A     5
238         9235  404940.0  1112.0 -11.23  White              A     5
239        37882  294903.0  1783.0  -7.80   Blue              O     5

In [5]:
df['Spectral_Class'].unique()

array(['M', 'B', 'A', 'F', 'O', 'K', 'G'], dtype=object)

In [6]:
#Removing B,A,F ,K ,G from the spectral_class 

indexes=df[(df['Spectral_Class']=='A') | (df['Spectral_Class'] =='B')| (df['Spectral_Class'] =='F')|(df['Spectral_Class'] =='G')|(df['Spectral_Class'] =='K')].index
df.drop(indexes,inplace=True)

In [7]:
df.head()

Temperature         L       R    A_M Color Spectral_Class  Type
0         3068  0.002400  0.1700  16.12   Red              M     0
1         3042  0.000500  0.1542  16.60   Red              M     0
2         2600  0.000300  0.1020  18.70   Red              M     0
3         2800  0.000200  0.1600  16.65   Red              M     0
4         1939  0.000138  0.1030  20.06   Red              M     0

In [8]:
df.tail()

Temperature         L       R    A_M Color Spectral_Class  Type
231        38234  272830.0  1356.0  -9.29  Blue              O     5
232        32489  648430.0  1948.5 -10.84  Blue              O     5
235        38940  374830.0  1356.0  -9.93  Blue              O     5
236        30839  834042.0  1194.0 -10.63  Blue              O     5
239        37882  294903.0  1783.0  -7.80  Blue              O     5

In [9]:
#Encoding M and O into 1 and 2
df['Spectral_Class'] = df['Spectral_Class'].map({'M':1,'O':2})

In [10]:
df.head()

Temperature         L       R    A_M Color  Spectral_Class  Type
0         3068  0.002400  0.1700  16.12   Red               1     0
1         3042  0.000500  0.1542  16.60   Red               1     0
2         2600  0.000300  0.1020  18.70   Red               1     0
3         2800  0.000200  0.1600  16.65   Red               1     0
4         1939  0.000138  0.1030  20.06   Red               1     0

In [11]:
df.tail()

Temperature         L       R    A_M Color  Spectral_Class  Type
231        38234  272830.0  1356.0  -9.29  Blue               2     5
232        32489  648430.0  1948.5 -10.84  Blue               2     5
235        38940  374830.0  1356.0  -9.93  Blue               2     5
236        30839  834042.0  1194.0 -10.63  Blue               2     5
239        37882  294903.0  1783.0  -7.80  Blue               2     5

In [12]:
df.drop("Color", axis=1, inplace=True)

In [13]:
#Differentiating between dependent and independent variables 
X = df.iloc[:,:-2]
Y = df.iloc[:,-2]

In [14]:
X

Temperature              L          R    A_M
0           3068       0.002400     0.1700  16.12
1           3042       0.000500     0.1542  16.60
2           2600       0.000300     0.1020  18.70
3           2800       0.000200     0.1600  16.65
4           1939       0.000138     0.1030  20.06
..           ...            ...        ...    ...
231        38234  272830.000000  1356.0000  -9.29
232        32489  648430.000000  1948.5000 -10.84
235        38940  374830.000000  1356.0000  -9.93
236        30839  834042.000000  1194.0000 -10.63
239        37882  294903.000000  1783.0000  -7.80

[151 rows x 4 columns]

In [15]:
Y

0      1
1      1
2      1
3      1
4      1
      ..
231    2
232    2
235    2
236    2
239    2
Name: Spectral_Class, Length: 151, dtype: int64

# LINEAR REGRESSION IMPLEMENTATIONS

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=4)

In [19]:
X_train

Temperature              L        R     A_M
67          2817       0.000980   0.0911  16.450
186         2968       0.000461   0.1190  17.450
1           3042       0.000500   0.1542  16.600
160        25390  223000.000000  57.0000  -5.920
132         3100       0.008000   0.3100  11.170
..           ...            ...      ...     ...
70          3345       0.021000   0.2730  12.300
129         2731       0.000437   0.0856  18.090
165         7282  131000.000000  24.0000  -7.220
195         3598       0.002700   0.6700  13.667
188         2778       0.000849   0.1120  19.450

[120 rows x 4 columns]

In [20]:
X_test

Temperature              L          R     A_M
184         3453       0.000621     0.0773  17.080
18          3192       0.003620     0.1967  13.530
199         3463       0.002700     0.6750  14.776
167        26373  198000.000000    39.0000  -5.830
169         9373  424520.000000    24.0000  -5.990
120         3323       0.000430     0.0912  17.160
125         3225       0.000760     0.1210  19.630
14          2650       0.000600     0.1400  11.782
5           2840       0.000650     0.1100  16.980
214        34190  198200.000000     6.3900  -4.570
44          3008  280000.000000    25.0000  -6.000
11          3129       0.012200     0.3761  11.790
12          3134       0.000400     0.1960  13.210
103        17120  235000.000000    83.0000  -6.890
180         2831       0.000231     0.0915  16.210
54          3650  310000.000000  1324.0000  -7.790
99         36108  198000.000000    10.2000  -4.400
2           2600       0.000300     0.1020  18.700
43          3200  195000.000000    17.0000  -7.220
190         3462       0.005300     0.1480  11.470
55          3450  263000.000000  1349.0000 -11.750
191         3257       0.002400     0.4600  10.730
108        24345  142000.000000    57.0000  -6.240
45          3600  320000.000000    29.0000  -6.600
48          3625  184000.000000    84.0000  -6.740
19          3441       0.039000     0.3510  11.180
61          3432       0.000670     0.1900  16.940
16          2799       0.001800     0.1600  14.790
30         39000  204000.000000    10.6000  -4.700
163         5752  245000.000000    97.0000  -6.630
126         2935       0.000870     0.0932  16.880

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
model = LinearRegression()


In [23]:
#Training part
model.fit(X_train,y_train)

LinearRegression()

In [24]:
#Making Predictions
predictions = model.predict(X_test)

In [25]:
predictions

array([0.98274814, 1.03418383, 1.02085758, 2.03731565, 1.65310558,
       0.9778727 , 0.93441209, 1.0482567 , 0.9676475 , 2.24084722,
       1.43289703, 1.06112768, 1.03788264, 1.79939434, 0.9801189 ,
       1.05973391, 2.28909544, 0.93270238, 1.43374335, 1.07557967,
       1.09633962, 1.08209384, 1.96483503, 1.47043767, 1.41173782,
       1.07972629, 0.98444845, 1.0026635 , 2.37481282, 1.48321558,
       0.97189823])

In [34]:
from sklearn.metrics import r2_score , mean_squared_error, mean_absolute_error

In [35]:
mse = mean_squared_error(y_test,predictions)
lr_score = r2_score(y_test, predictions)
mae =  mean_absolute_error(y_test, predictions)
rmse = mean_squared_error(y_test,predictions,squared=False)

In [28]:
mse

0.049405629251817476

In [29]:
lr_score

0.7419629907011055

In [32]:
mae

0.15022365688063644

In [36]:
rmse

0.2222737709488402

# RANDOM FOREST REGRESSOR IMPLEMENTATIONS

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=4)

In [38]:
from sklearn.ensemble import RandomForestRegressor


In [39]:
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)


In [40]:
rf.fit(X_train,y_train)


RandomForestRegressor(n_estimators=1000, random_state=42)

In [41]:
y_predictions = rf.predict(X_test)

In [42]:
y_predictions


array([1.   , 1.   , 1.   , 2.   , 2.   , 1.   , 1.   , 1.   , 1.   ,
       2.   , 1.   , 1.   , 1.   , 2.   , 1.   , 1.   , 2.   , 1.   ,
       1.   , 1.   , 1.   , 1.   , 2.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 2.   , 1.621, 1.   ])

In [43]:
from sklearn.metrics import mean_squared_error ,r2_score , mean_absolute_error

In [45]:
mse = mean_squared_error(y_test,y_predictions)
mae = mean_absolute_error(y_test,y_predictions)
rf_score = r2_score(y_test,y_predictions)
rmse = mean_squared_error(y_test,y_predictions, squared=False)

In [46]:
mse

0.00463358064516129

In [47]:
rmse

0.06807040946814769

In [48]:
rf_score

0.9757996141304348

In [49]:
mae 

0.012225806451612904

# SUPPORT VECTOR REGRESSOR IMPLEMENTATIONS


In [50]:
#Dividing the datas between independent and dependent variable 
X = df.iloc[:,:-2]
Y = df.iloc[:,-2]


In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
#Scaling down the values for better training the model
from sklearn.preprocessing import StandardScaler 
sc_X = StandardScaler() 
sc_Y = StandardScaler() 
X = sc_X.fit_transform(X) 
Y = Y.values.reshape(-1,1)

In [53]:
from sklearn.svm import SVR 
regressor = SVR(kernel = 'rbf') 
regressor.fit(X, Y)

/Users/soumobratamanna/Documents/Data_Science_Projects/tensorflow-test/env/lib/python3.8/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [54]:
predictions = regressor.predict(X)


In [55]:
predictions

array([1.07482894, 1.07546342, 1.07513481, 1.06975899, 1.07376919,
       1.07190202, 1.06827316, 1.06827972, 1.06959452, 1.06531263,
       1.09539984, 1.07472711, 1.07373509, 1.09726925, 1.0576597 ,
       1.08067764, 1.06476463, 1.09875346, 1.07554968, 1.08766141,
       1.90004784, 1.13077851, 1.21126847, 1.06200147, 1.07216107,
       1.10003305, 1.20566228, 1.10749654, 1.09071687, 1.1006094 ,
       1.06141787, 1.08441845, 1.09372826, 1.1001918 , 1.07747763,
       1.06755652, 1.0705745 , 1.06881694, 1.10007546, 1.08143896,
       1.0821774 , 1.08604053, 1.07257384, 1.0717117 , 1.08267587,
       1.08318692, 1.08004961, 1.06948979, 1.07204846, 1.08457382,
       1.08178686, 1.09769781, 1.07936789, 1.07529088, 1.09277026,
       1.07663325, 1.06590824, 1.08239812, 1.05695003, 1.07450463,
       1.91384041, 1.89974103, 2.07330592, 2.09555992, 1.74984859,
       1.98903757, 2.05645827, 1.89961809, 2.06849803, 1.91864601,
       1.08736619, 1.0814856 , 1.09244448, 1.09589773, 1.10009

In [56]:
from sklearn.metrics import mean_squared_error ,r2_score, mean_absolute_error

In [57]:
mse = mean_squared_error(Y,predictions)
rmse = mean_squared_error(Y,predictions, squared = False)
mae = mean_absolute_error(Y,predictions)
svr_score = r2_score(Y,predictions)

In [58]:
mse

0.013948946244273707

In [59]:
mae

0.09425839802568063

In [60]:
rmse

0.11810565712222978

In [61]:
svr_score

0.9283671343883593