# Tensorflow 

Tensorflow is a computational framework for building Machine Learning and Deep Learning models

Each tensor has a datatype and shape 
Datatyes - float32 , int32 , string etc etc 
Shapes- Represents the dimensions of data . 

We can implement various mathematical operations on tensorflow.

Rank/Degree means the number of dimensions involved in the tensor 

Types of Tensors 
1. Variables - It is a state or value that can be modified by performing operations on it and is trainable.
2. Constant - It is a fixed value and are not trainable .
3. Placeholder - Used for input data , It allows us to create our operations and build our computation graph, without needing the data
4. SparseTensor - It is a dataset in which most of the entries are zero , enable efficient storage and processing of tensors that contain a lot of zero values.

With the execption of Variable all these tensors are immuttable, meaning their value may not change during execution.

# Initialization of  Tensors 

In [1]:
import tensorflow as tf

In [2]:
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

Metal device set to: Apple M1


2022-09-27 19:33:57.458923: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-09-27 19:33:57.459777: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [3]:
string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>

In [4]:
number

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>

In [5]:
floating

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>

In [6]:
#Rank/Degree of tensors 
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [7]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [8]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [9]:
x = tf.constant(3.2)


In [10]:
x

<tf.Tensor: shape=(), dtype=float32, numpy=3.2>

In [11]:
x.shape

TensorShape([])

In [12]:
x = tf.constant(4,shape=(2,3), dtype = tf.float32)

In [13]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)>

In [14]:
x = tf.constant([[1,2,3],[2,3,4]])


In [15]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4]], dtype=int32)>

In [16]:
x = tf.ones((3,3))

In [17]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
x = tf.zeros((2,3))

In [19]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [20]:
#Printing identity matrix 
#eye stands for identity matrix 
x = tf.eye(3)

In [21]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [22]:
#Normal Distribution 
x = tf.random.normal((3,3),mean=0,stddev = 1)

In [23]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.4341177 , -0.41762212, -1.6158755 ],
       [ 0.09949732,  0.20530444,  0.02223607],
       [-0.44558287, -0.4655861 ,  0.7622815 ]], dtype=float32)>

In [24]:
#Uniform distribution
x = tf.random.uniform((3,3),minval = 0,maxval = 1)

In [25]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.32112324, 0.5952555 , 0.00218427],
       [0.69839275, 0.18520725, 0.49277163],
       [0.26580012, 0.70263076, 0.9368688 ]], dtype=float32)>

In [26]:
#Range function 
x = tf.range(9)

In [27]:
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [28]:
x = tf.range(start = 0, limit = 12, delta = 2)

In [29]:
x

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  2,  4,  6,  8, 10], dtype=int32)>

In [30]:
#Changing data types 
x = tf.range(start = 0, limit = 12, delta = 2)
y = tf.cast(x,dtype = tf.float32)

In [31]:
y

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 0.,  2.,  4.,  6.,  8., 10.], dtype=float32)>

# Mathematical Operations

In [32]:
x = tf.constant([1,2,3])
y = tf.constant([1,2,3])


In [33]:
z = tf.add(x,y)

In [34]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [35]:
z = tf.subtract(x,y)


In [36]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [37]:
z = tf.multiply(x,y)


In [38]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [39]:
z = tf.divide(x,y)


In [40]:
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 1., 1.])>

In [41]:
z = tf.tensordot(x,y,axes = 1)

In [42]:
z

<tf.Tensor: shape=(), dtype=int32, numpy=14>

In [43]:
z = tf.reduce_sum(x+y,axis=0)

In [44]:
z

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [45]:
z = x ** 5

In [46]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243], dtype=int32)>

In [47]:
#Matrix Multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))


In [48]:
z = tf.matmul(x,y)

In [49]:
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.35886627, -3.1241467 ,  0.01380903, -4.0290937 ],
       [-2.3348947 , -2.0281982 ,  0.55821663, -1.2793354 ]],
      dtype=float32)>

In [50]:
z = x @ y

In [51]:
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.35886627, -3.1241467 ,  0.01380903, -4.0290937 ],
       [-2.3348947 , -2.0281982 ,  0.55821663, -1.2793354 ]],
      dtype=float32)>

# Indexing Operation

In [58]:
x = tf.constant([1,2,3,4,5,6,7,8,9])

In [59]:
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [60]:
print(x[:])

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [61]:
print(x[:-2])

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)


In [62]:
print(x[-1])

tf.Tensor(9, shape=(), dtype=int32)


In [63]:
print(x[:2])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [64]:
print(x[2:])

tf.Tensor([3 4 5 6 7 8 9], shape=(7,), dtype=int32)


In [65]:
print(x[2:-2])

tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int32)


In [66]:
print(x[::])

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [67]:
print(x[::2])

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [68]:
print(x[::-1])

tf.Tensor([9 8 7 6 5 4 3 2 1], shape=(9,), dtype=int32)


In [69]:
print(x[1::])

tf.Tensor([2 3 4 5 6 7 8 9], shape=(8,), dtype=int32)


In [70]:
#Gathering only 2 digits from the lists 
indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)


In [71]:
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [72]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])


In [73]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [74]:
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [75]:
print(x[0:2])


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


# Reshaping 

In [76]:
x = tf.range(9)

In [77]:
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [78]:
z = tf.reshape(x,(3,3))

In [79]:
z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [80]:
#Transpose operation
x = tf.constant([[1,2,3],[4,5,6]])

In [81]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [82]:
z = tf.transpose(x)

In [83]:
z

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [84]:
z = tf.transpose(x, perm = [1,0])

In [85]:
z

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>