# Tensorflow 

Tensorflow is a computational framework for building Machine Learning Models 

# Initialization of  Tensors 

In [1]:
import tensorflow as tf

In [5]:
x = tf.constant(3.2)


In [6]:
x

<tf.Tensor: shape=(), dtype=float32, numpy=3.2>

In [7]:
x.shape

TensorShape([])

In [11]:
x = tf.constant(4,shape=(2,3), dtype = tf.float32)

In [12]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)>

In [13]:
x = tf.constant([[1,2,3],[2,3,4]])


In [14]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4]], dtype=int32)>

In [15]:
x = tf.ones((3,3))

In [16]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [17]:
x = tf.zeros((2,3))

In [19]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [22]:
#Printing identity matrix 
#eye stands for identity matrix 
x = tf.eye(3)

In [23]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [28]:
#Normal Distribution 
x = tf.random.normal((3,3),mean=0,stddev = 1)

In [29]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.8939794 , -0.1330358 , -0.35000512],
       [-1.0187167 ,  0.40738305, -0.21277711],
       [ 1.6319302 , -0.01891889,  0.5004877 ]], dtype=float32)>

In [30]:
#Uniform distribution
x = tf.random.uniform((3,3),minval = 0,maxval = 1)

In [31]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.28285134, 0.74089515, 0.36541724],
       [0.9146714 , 0.26776695, 0.72022855],
       [0.64375496, 0.09948933, 0.89645195]], dtype=float32)>

In [32]:
#Range function 
x = tf.range(9)

In [33]:
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [34]:
x = tf.range(start = 0, limit = 12, delta = 2)

In [35]:
x

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  2,  4,  6,  8, 10], dtype=int32)>

In [36]:
#Changing data types 
x = tf.range(start = 0, limit = 12, delta = 2)
y = tf.cast(x,dtype = tf.float32)

In [37]:
y

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 0.,  2.,  4.,  6.,  8., 10.], dtype=float32)>

# Mathematical Operations

In [40]:
x = tf.constant([1,2,3])
y = tf.constant([1,2,3])


In [42]:
z = tf.add(x,y)

In [43]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [44]:
z = tf.subtract(x,y)


In [45]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [47]:
z = tf.multiply(x,y)


In [48]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [49]:
z = tf.divide(x,y)


In [50]:
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 1., 1.])>

In [55]:
z = tf.tensordot(x,y,axes = 1)

In [56]:
z

<tf.Tensor: shape=(), dtype=int32, numpy=14>

In [62]:
z = tf.reduce_sum(x+y,axis=0)

In [63]:
z

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [64]:
z = x ** 5

In [65]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243], dtype=int32)>

In [69]:
#Matrix Multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))


In [70]:
z = tf.matmul(x,y)

In [71]:
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.8050419 ,  0.44947863, -0.60530776,  0.80879676],
       [ 1.2560707 ,  0.633409  , -0.844085  , -1.3908007 ]],
      dtype=float32)>

In [72]:
z = x @ y

In [73]:
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.8050419 ,  0.44947863, -0.60530776,  0.80879676],
       [ 1.2560707 ,  0.633409  , -0.844085  , -1.3908007 ]],
      dtype=float32)>

# Indexing Operaation

In [74]:
x = tf.constant([1,2,3,4,5,6,7,8,9])

In [75]:
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [76]:
print(x[:])

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [77]:
print(x[:-2])

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)


In [78]:
print(x[-1])

tf.Tensor(9, shape=(), dtype=int32)


In [79]:
print(x[:2])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [80]:
print(x[2:])

tf.Tensor([3 4 5 6 7 8 9], shape=(7,), dtype=int32)


In [81]:
print(x[2:-2])

tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int32)


In [82]:
print(x[::])

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [83]:
print(x[::2])

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [84]:
print(x[::-1])

tf.Tensor([9 8 7 6 5 4 3 2 1], shape=(9,), dtype=int32)


In [85]:
print(x[1::])

tf.Tensor([2 3 4 5 6 7 8 9], shape=(8,), dtype=int32)


In [86]:
#Gathering only 2 digits from the lists 
indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)


In [87]:
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [88]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])


In [89]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [90]:
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [93]:
print(x[0:2])


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


# Reshaping 

In [102]:
x = tf.range(9)

In [103]:
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [104]:
z = tf.reshape(x,(3,3))

In [105]:
z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [110]:
#Transpose operation
x = tf.constant([[1,2,3],[4,5,6]])

In [111]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [112]:
z = tf.transpose(x)

In [113]:
z

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [115]:
z = tf.transpose(x, perm = [1,0])

In [116]:
z

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>